# Generated by Django 5.0.1 on 2024-02-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="date",
            new_name="start_date",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="time",
            new_name="start_time",
        ),
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateField(default="2024-12-13"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="end_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(default="Yaba", max_length=225),
            preserve_default=False,
        ),
    ]
