# Generated by Django 5.0.1 on 2024-02-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_rename_date_event_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
