# Generated by Django 5.0.1 on 2024-03-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_event_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.URLField(),
        ),
    ]
