# Generated by Django 5.0.1 on 2024-03-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_event_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
