# Generated by Django 5.0.1 on 2024-01-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="display_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="state_of_residence",
            field=models.CharField(
                blank=True,
                choices=[
                    ("abia", "Abia"),
                    ("adamawa", "Adamawa"),
                    ("akwa_ibom", "Akwa Ibom"),
                    ("anambra", "Anambra"),
                    ("bauchi", "Bauchi"),
                    ("bayelsa", "Bayelsa"),
                    ("benue", "Benue"),
                    ("borno", "Borno"),
                    ("cross_river", "Cross River"),
                    ("delta", "Delta"),
                    ("ebonyi", "Ebonyi"),
                    ("edo", "Edo"),
                    ("ekiti", "Ekiti"),
                    ("enugu", "Enugu"),
                    ("gombe", "Gombe"),
                    ("imo", "Imo"),
                    ("jigawa", "Jigawa"),
                    ("kaduna", "Kaduna"),
                    ("kano", "Kano"),
                    ("katsina", "Katsina"),
                    ("kebbi", "Kebbi"),
                    ("kogi", "Kogi"),
                    ("kwara", "Kwara"),
                    ("lagos", "Lagos"),
                    ("nasarawa", "Nasarawa"),
                    ("niger", "Niger"),
                    ("ogun", "Ogun"),
                    ("ondo", "Ondo"),
                    ("osun", "Osun"),
                    ("oyo", "Oyo"),
                    ("plateau", "Plateau"),
                    ("rivers", "Rivers"),
                    ("sokoto", "Sokoto"),
                    ("taraba", "Taraba"),
                    ("yobe", "Yobe"),
                    ("zamfara", "Zamfara"),
                    ("federal_capital_territory", "FCT"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_field",
            field=models.CharField(
                blank=True,
                choices=[
                    ("billboard_owner", "Billboard Owner"),
                    ("state_agent", "State Agent"),
                    ("advertising_agent", "Advertising Agent"),
                    ("business_owner", "Business Owner"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
