# Generated by Django 5.0.1 on 2024-01-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_customuser_state_of_residence"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="password_reset_otp",
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="password_reset_otp_created_at",
            field=models.DateTimeField(null=True),
        ),
    ]
