# Generated by Django 5.0.1 on 2024-01-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_customuser_password_reset_otp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("abia", "Abia"),
                            ("adamawa", "Adamawa"),
                            ("akwa_ibom", "Akwa Ibom"),
                            ("anambra", "Anambra"),
                            ("bauchi", "Bauchi"),
                            ("bayelsa", "Bayelsa"),
                            ("benue", "Benue"),
                            ("borno", "Borno"),
                            ("cross_river", "Cross River"),
                            ("delta", "Delta"),
                            ("ebonyi", "Ebonyi"),
                            ("edo", "Edo"),
                            ("ekiti", "Ekiti"),
                            ("enugu", "Enugu"),
                            ("gombe", "Gombe"),
                            ("imo", "Imo"),
                            ("jigawa", "Jigawa"),
                            ("kaduna", "Kaduna"),
                            ("kano", "Kano"),
                            ("katsina", "Katsina"),
                            ("kebbi", "Kebbi"),
                            ("kogi", "Kogi"),
                            ("kwara", "Kwara"),
                            ("lagos", "Lagos"),
                            ("nasarawa", "Nasarawa"),
                            ("niger", "Niger"),
                            ("ogun", "Ogun"),
                            ("ondo", "Ondo"),
                            ("osun", "Osun"),
                            ("oyo", "Oyo"),
                            ("plateau", "Plateau"),
                            ("rivers", "Rivers"),
                            ("sokoto", "Sokoto"),
                            ("taraba", "Taraba"),
                            ("yobe", "Yobe"),
                            ("zamfara", "Zamfara"),
                            ("fct_abuja", "FCT (Abuja)"),
                        ],
                        max_length=225,
                    ),
                ),
            ],
        ),
    ]
