# Generated by Django 5.0.1 on 2024-01-31 18:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_state"),
        ("maintenance", "0002_alter_maintenance_state"),
    ]

    operations = [
        migrations.DeleteModel(
            name="State",
        ),
    ]
