# Generated by Django 5.0.1 on 2024-02-08 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_customuser_country_alter_customuser_display_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="state_of_residence",
            new_name="state",
        ),
    ]
