# Generated by Django 5.0.1 on 2024-02-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_remove_subscription_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="paystack_email_token",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="paystack_sub_code",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
