# Generated by Django 5.0.1 on 2024-03-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0003_subscription_paystack_email_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="paystack_ref",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
