# Generated by Django 5.0.1 on 2024-03-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0004_subscription_paystack_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="temp_plan",
            field=models.CharField(
                choices=[("free", "Free"), ("basic", "Basic"), ("pro", "Pro")],
                default="free",
                max_length=20,
                null=True,
            ),
        ),
    ]
