# Generated by Django 5.0.1 on 2024-03-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0005_subscription_temp_plan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="temp_plan",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
