# Generated by Django 5.0.1 on 2024-02-01 17:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0003_maintenance_fixed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Maintenance",
            new_name="MaintenanceBooking",
        ),
    ]
