# Generated by Django 5.0.1 on 2024-02-05 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0004_rename_maintenance_maintenancebooking"),
    ]

    operations = [
        migrations.RenameField(
            model_name="maintenancebooking",
            old_name="fixed",
            new_name="is_fixed",
        ),
    ]
