# Generated by Django 5.0.1 on 2024-04-07 19:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0006_alter_maintenancebooking_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maintenancebooking",
            name="state",
        ),
    ]
