# Generated by Django 5.0.1 on 2024-01-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requirements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billboardrequirement",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="billboardrequirement",
            name="link",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
