# Generated by Django 5.0.1 on 2024-01-30 16:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("requirements", "0002_alter_billboardrequirement_document_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billboardrequirement",
            name="document",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
