# Generated by Django 5.0.1 on 2024-02-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requirements", "0003_alter_billboardrequirement_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billboardrequirement",
            name="state",
            field=models.CharField(
                choices=[
                    ("abia", "Abia"),
                    ("adamawa", "Adamawa"),
                    ("akwa-ibom", "Akwa Ibom"),
                    ("anambra", "Anambra"),
                    ("bauchi", "Bauchi"),
                    ("bayelsa", "Bayelsa"),
                    ("benue", "Benue"),
                    ("borno", "Borno"),
                    ("cross-river", "Cross River"),
                    ("delta", "Delta"),
                    ("ebonyi", "Ebonyi"),
                    ("edo", "Edo"),
                    ("ekiti", "Ekiti"),
                    ("enugu", "Enugu"),
                    ("fct", "Fct"),
                    ("gombe", "Gombe"),
                    ("imo", "Imo"),
                    ("jigawa", "Jigawa"),
                    ("kaduna", "Kaduna"),
                    ("kano", "Kano"),
                    ("katsina", "Katsina"),
                    ("kebbi", "Kebbi"),
                    ("kogi", "Kogi"),
                    ("kwara", "Kwara"),
                    ("lagos", "Lagos"),
                    ("nasarawa", "Nasarawa"),
                    ("niger", "Niger"),
                    ("ogun", "Ogun"),
                    ("ondo", "Ondo"),
                    ("osun", "Osun"),
                    ("oyo", "Oyo"),
                    ("plateau", "Plateau"),
                    ("rivers", "Rivers"),
                    ("sokoto", "Sokoto"),
                    ("taraba", "Taraba"),
                    ("yobe", "Yobe"),
                    ("zamfara", "Zamfara"),
                ],
                max_length=255,
            ),
        ),
    ]
