# Generated by Django 5.0.1 on 2024-01-23 17:35

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Billboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", cloudinary.models.CloudinaryField(max_length=255)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("potrait", "Potrait"),
                            ("large_format", "Large Format"),
                            ("48_sheet", "48 Sheet"),
                            ("spectacular_billboard", "Spectacular Billboard"),
                            ("gantry", "Gantry"),
                            ("unipole", "Unipole"),
                        ],
                        max_length=21,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("available_date_from", models.DateField()),
                ("available_date_to", models.DateField()),
                ("target_audience_from", models.PositiveIntegerField()),
                ("target_audience_to", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
