# Generated by Django 5.0.1 on 2024-01-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billboards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="billboard",
            name="booked",
            field=models.BooleanField(default=False),
        ),
    ]
