# Generated by Django 5.0.1 on 2024-01-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billboards", "0003_remove_billboard_available_date_from_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billboard",
            options={"ordering": ["-is_verified"]},
        ),
        migrations.AddField(
            model_name="billboard",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
