# Generated by Django 5.0.1 on 2024-01-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billboards", "0004_alter_billboard_options_billboard_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="billboard",
            name="is_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
