# Generated by Django 5.0.1 on 2024-01-28 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billboards", "0005_billboard_is_verified_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billboard",
            options={"ordering": ["-is_verified_at"]},
        ),
    ]
