# Generated by Django 5.0.1 on 2024-02-05 15:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billboards", "0008_billboard_price_alter_billboard_is_verified"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billboard",
            old_name="booked",
            new_name="is_booked",
        ),
    ]
