# Generated by Django 5.0.1 on 2024-02-05 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0003_booking_paystack_ref"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="paid",
            new_name="is_paid",
        ),
    ]
