# Generated by Django 5.0.1 on 2024-01-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="caption",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
